### ISSUE TITLE
Attribute :type has already been defined (Dry::Struct::RepeatedAttributeError)

### ISSUE THREAD

**Issue by sidguptajhs** [dry-rb/dry-struct#109]
My scenarios is like this:

data.rb
```
class Data < Dry::Struct::Value
  attribute :type, Dry::Types['strict.string']
end
```

v1_model.rb
```
require_relative 'data.rb'
```

v2_model.rb
```
require_relative 'data.rb'
```

When I try to load my application, I get the error:

> Attribute :type has already been defined (Dry::Struct::RepeatedAttributeError)

I know this issue has come before and the recommended path is to have dry * files load eagerly, but I can't do it because similar code is spread out all across my application and I'd have to pretty much eager load everything in app/models before hand, which will affect the rails auto reload feature in development.

Right now I'm patching this by:
```
module Dry
  class Struct
    module ClassInterface
      # This is to avoid errors such as -> Attribute :type has already been defined (Dry::Struct::RepeatedAttributeError)
      def check_schema_duplication(schema)
      end
    end
  end
end
```

What I'd want to recommend is to have an option in Dry::Struct to disable repeated attribute check.

**Comment by flash-gordon** [comment]
This is not the right way to "fix" it. You load your class definition more than once, this is not safe in general, regardless of dry-struct. What you do is running the class definition once again, it means executing again all top-level and class-level code residing in the file. It 1) can lead to subtle bugs 2) slower, that's why I'm not going to provide an "official" workaround.
Normally, you won't get this kind of errors, my wild guess it's somehow caused by using `require_relative` in your code. If you want to fix the issue properly I'd suggest starting to look into this.

This is not a bug nor an approved feature request. Please, ask questions (including those about features) on our forum or in a chat (see CONTRIBUTING.md).

**Comment by abrisse** [comment]
I post it here to help developers that have circular references between multiple `Dry::Struct` classes (if 2 classes refers to each other).

A clean solution would like to begin to declare only the class definition.

```ruby
# File A.rb
class A < Dry::Struct
  attribute? :b, B
end

# File B.rb
class B < Dry::Struct
  attribute? :a, A
end

# Top file
class A < Dry::Struct; end
class B < Dry::Struct; end

require_relative 'a'
require_relative 'b'
```
