### ISSUE TITLE
Nested optional struct does not inherit `transform_keys(&:to_sym)`

### ISSUE THREAD

**Issue by hovsater** [dry-rb/dry-struct#187]
## Describe the bug

Nested optional structs does not inherit key transformations.

## To Reproduce

```ruby
class MyStruct < Dry::Struct
  transform_keys(&:to_sym)
  
  attribute :foo, Types::String
  attribute :bar, Dry::Struct.optional do
    attribute :baz, Types::String
  end
end
```

```ruby
MyStruct.new({ "foo" => "foo", "bar" => { "baz" => "baz" } })
```

## Expected behavior

It should inherit key transformations from its parent.

## My environment

- Affects my production application: YES
- Ruby version: 3.2.1
- OS: macOS 13.3.1

**Comment by flash-gordon** [comment]
They can't be inherited the way you show, they have to share the same parent class. In your example the closest common ancestor is `Dry::Struct`, it doesn't have a key transformation. I suggest you use a custom parent class

```ruby
class MyStructBase < Dry::Struct
  transform_keys(&:to_sym)
end

class MyStruct < MyStructBase
  attribute :foo, Types::String
  attribute :bar, MyStructBase.optional do
    attribute :baz, Types::String
  end
end
```

**Comment by hovsater** [comment]
Right, that makes sense. At the same time it's somewhat awkward that you get inheritance for free for nested structures without a specific type, but if you want an optional nested structure, you'll have to break out a base class to keep the API the same.

**Comment by flash-gordon** [comment]
True, I also felt the ergonomics aren't perfect, I couldn't come up with a useful shortcut, though. In your example, it makes sense to apply `.optional` to the resulting type, that is instead of calling `.optional` on the base class, you call `.optional` on the result. Unfortunately, there's no convenient place to do it :( For instance, this won't work:
```ruby
attribute :bar {
  attribute :baz, :string
}.optional
```
because it'll send `optional` to the wrong receiver.

However, it is possible to define your own method like `optional_attribute` that does the job under the hood. It's probably the best option atm
