### ISSUE TITLE
equality of structs

### ISSUE THREAD

**Issue by fledman** [dry-rb/dry-struct#79]
All Struct equality comparisons are by object_id. This probably makes sense for most Class objects, but isn't very useful here: 
```ruby
> s1=Dry.Struct()
 => #<Class:0x00007fe7b80860e0> 
> s2=Dry.Struct()
 => #<Class:0x00007fe7b82ee198>
> s1.input == s2.input && s1.meta == s2.meta
 => true
> [s1 == s2, s1.eql?(s2), s1 === s2]
 => [false, false, false]
```
This is mostly an issue with `.meta`, since it is currently implemented by generating a subclass:
```ruby
> start = Dry.Struct.meta(foo: 'bar')
 => #<Class:0x00007fe7b82ec3e8> 
> flip = start.meta(foo: 'woot')
 => #<Class:0x00007fe7b78ed2c0> 
> flop = flip.meta(foo: 'bar')
 => #<Class:0x00007fe7b82cc9d0> 
> start.input == flop.input && start.meta == flop.meta
 => true 
> start == flop
 => false 
```

**Comment by GustavoCaso** [comment]
Maybe I'm wrong by but the look at the code base I think the equality is done over `__attrinutes__` on the instance level.

```ruby
irb(main):007:0> s1 = Dry::Struct.new
=> #<Dry::Struct>
irb(main):008:0> s2 = Dry::Struct.new
=> #<Dry::Struct>
irb(main):009:0> s1 == s2
=> true
irb(main):010:0> s1.object_id == s2.object_id
=> false
irb(main):012:0> s1.attributes == s2.attributes
=> true
```

Regarding meta, question a struct without meta is not the same as that struct with meta, here is a conversation regarding this topic https://github.com/dry-rb/dry-struct/issues/47

**Comment by flash-gordon** [comment]
@fledman this is expected, we're not going to mess with ruby here. Structs are usually (in like 99% of cases) assigned to constants and mean different data types which are _isomorphic_ to each other but still different. We could have `isomorphic?` or whatever less weird name for this or, say, keep a reference to the original class. However, first you need to describe your use case. Since I don't find this a bug (yet) nor a feature request, please move this discussion to [the forum](https://discourse.dry-rb.org/), we can sort it out there.
